/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcingRouteImport } from './routes/sourcing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as DiligenceRouteImport } from './routes/diligence'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoundersIndexRouteImport } from './routes/founders.index'
import { Route as FoundersIdRouteImport } from './routes/founders.$id'

const SourcingRoute = SourcingRouteImport.update({
  id: '/sourcing',
  path: '/sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const DiligenceRoute = DiligenceRouteImport.update({
  id: '/diligence',
  path: '/diligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersIndexRoute = FoundersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FoundersRoute,
} as any)
const FoundersIdRoute = FoundersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FoundersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diligence': typeof DiligenceRoute
  '/founders': typeof FoundersRouteWithChildren
  '/screening': typeof ScreeningRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing': typeof SourcingRoute
  '/founders/$id': typeof FoundersIdRoute
  '/founders/': typeof FoundersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diligence': typeof DiligenceRoute
  '/screening': typeof ScreeningRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing': typeof SourcingRoute
  '/founders/$id': typeof FoundersIdRoute
  '/founders': typeof FoundersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diligence': typeof DiligenceRoute
  '/founders': typeof FoundersRouteWithChildren
  '/screening': typeof ScreeningRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sourcing': typeof SourcingRoute
  '/founders/$id': typeof FoundersIdRoute
  '/founders/': typeof FoundersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diligence'
    | '/founders'
    | '/screening'
    | '/settings'
    | '/sitemap.xml'
    | '/sourcing'
    | '/founders/$id'
    | '/founders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diligence'
    | '/screening'
    | '/settings'
    | '/sitemap.xml'
    | '/sourcing'
    | '/founders/$id'
    | '/founders'
  id:
    | '__root__'
    | '/'
    | '/diligence'
    | '/founders'
    | '/screening'
    | '/settings'
    | '/sitemap.xml'
    | '/sourcing'
    | '/founders/$id'
    | '/founders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiligenceRoute: typeof DiligenceRoute
  FoundersRoute: typeof FoundersRouteWithChildren
  ScreeningRoute: typeof ScreeningRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcingRoute: typeof SourcingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sourcing': {
      id: '/sourcing'
      path: '/sourcing'
      fullPath: '/sourcing'
      preLoaderRoute: typeof SourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diligence': {
      id: '/diligence'
      path: '/diligence'
      fullPath: '/diligence'
      preLoaderRoute: typeof DiligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders/': {
      id: '/founders/'
      path: '/'
      fullPath: '/founders/'
      preLoaderRoute: typeof FoundersIndexRouteImport
      parentRoute: typeof FoundersRoute
    }
    '/founders/$id': {
      id: '/founders/$id'
      path: '/$id'
      fullPath: '/founders/$id'
      preLoaderRoute: typeof FoundersIdRouteImport
      parentRoute: typeof FoundersRoute
    }
  }
}

interface FoundersRouteChildren {
  FoundersIdRoute: typeof FoundersIdRoute
  FoundersIndexRoute: typeof FoundersIndexRoute
}

const FoundersRouteChildren: FoundersRouteChildren = {
  FoundersIdRoute: FoundersIdRoute,
  FoundersIndexRoute: FoundersIndexRoute,
}

const FoundersRouteWithChildren = FoundersRoute._addFileChildren(
  FoundersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiligenceRoute: DiligenceRoute,
  FoundersRoute: FoundersRouteWithChildren,
  ScreeningRoute: ScreeningRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcingRoute: SourcingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
